version: '3.6'
services:
  user:
    image: trezker/user:latest
  producer:
    image: trezker/producer:latest
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/srv/www/static
      - ./dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    depends_on:
      - user
      - producer
