version: '3.6'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mysqldata:/var/lib/mysql
  user:
    build:
      context: ./user
    env_file:
      .env
    depends_on:
      - db
  producer:
    build:
      context: ./producer
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static:/srv/www/static
      - ./dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
    depends_on:
      - user
      - producer
