version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - 5001:8080
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./static:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web